apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ryodqnrk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ryodqnrk:62a7d6d86f0da7d939d09cccce782428b4385dc6@sha256:94ab2863136a08fa583d6795eef9a4b03a3911987fff3255be636ca896029ef2
        name: container-image  
